
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA CREATE FROM INSERT INTO LPAREN NAME RPAREN SELECT SHOW TABLE VALUES VAR bol int strstart : createcreate : CREATE create_bodycreate_body : TABLE NAME LPAREN values RPARENvalues : NAME type \n              | values COMMA NAME typetype : int \n            | str\n            | bol'
    
_lr_action_items = {'CREATE':([0,],[3,]),'$end':([1,2,4,14,],[0,-1,-2,-3,]),'TABLE':([3,],[5,]),'NAME':([5,7,15,],[6,8,16,]),'LPAREN':([6,],[7,]),'int':([8,16,],[11,11,]),'str':([8,16,],[12,12,]),'bol':([8,16,],[13,13,]),'RPAREN':([9,10,11,12,13,17,],[14,-4,-6,-7,-8,-5,]),'COMMA':([9,10,11,12,13,17,],[15,-4,-6,-7,-8,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'create':([0,],[2,]),'create_body':([3,],[4,]),'values':([7,],[9,]),'type':([8,16,],[10,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> create','start',1,'p_start','newParser.py',57),
  ('create -> CREATE create_body','create',2,'p_create','newParser.py',63),
  ('create_body -> TABLE NAME LPAREN values RPAREN','create_body',5,'p_create_body','newParser.py',68),
  ('values -> NAME type','values',2,'p_values','newParser.py',74),
  ('values -> values COMMA NAME type','values',4,'p_values','newParser.py',75),
  ('type -> int','type',1,'p_type','newParser.py',83),
  ('type -> str','type',1,'p_type','newParser.py',84),
  ('type -> bol','type',1,'p_type','newParser.py',85),
]
